version: '3'
services:
  nginx:
    # build: ./build/nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      # - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static_files:/usr/share/nginx/html

  # nginx2:
    # build: ./build/nginx2
    # container_name: nginx2
    # ports:
      # - "8081:443"