version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      # - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static_files:/usr/share/nginx/html

  https-portal:
    image: steveltn/https-portal:latest
    ports:
        - '80:80'
        - '443:443'
    links:
        # - wordpress
        - nginx
    restart: always
    # restart: unless-stopped
    environment:
        DOMAINS: 'kuro-140.com -> http://nginx:8080'
        #STAGE: 'local'
        STAGE: 'production'
        #FORCE_RENEW: 'true'
    # env_file:
      # - ./conf/conf.env
